### ISSUE TITLE
Show the optimization result using the example from the lecture

### ISSUE THREAD

**Issue by juri3333** [alex-bl/CompilerConstruction#82]
-Present the mC input program.
-Show the corresponding CFG.
-Show the relevant TAC before optimisation.
-Show the relevant TAC after optimisation.
-(optional) Show a table of the calucation, similar to the one from the lecture.
-Measure the impact of this optimisation.
--For a single run, the improvement will be quite hard to notice. Consider putting the lecture example in a loop with a fixed number of iterations.
--Present the measurement results.
--Tell which hardware was used for the measuring process.

**Comment by alex-bl** [comment]
Left out dueto lack of time.
